### ISSUE TITLE
CreateNewClipWithHarvestJob : IAM issue CreateHarvestJob

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/live-to-vod-workflow-using-aws-serverless-platform#2]
When I try to create a clip 
```
HTTP POST https://xxx.execute-api.eu-west-1.amazonaws.com/Prod/api/clip
```
I have an IAM issue

```
[ERROR] ClientError: An error occurred (AccessDeniedException) when calling the CreateHarvestJob operation: User: arn:aws:sts::xx:assumed-role/ServerlessLiveToVOD-CreateNewClipWithHarvestJobRol-G9HZQHKNLMOY/ServerlessLiveToVOD-CreateNewClipWithHarvestJob-1N47JG573CPRF is not authorized to perform: iam:PassRole on resource: arn:aws:iam::xxx:role/ServerlessLiveToVOD-MediaPackageS3Role-RCX5WBCX1ZN8
Traceback (most recent call last):
  File "/var/task/handler.py", line 37, in create_new_clip
    'RoleArn': MEDIA_PACKAGE_S3_ROLE_ARN
  File "/var/runtime/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

**Comment by markusz** [comment]
Thank you for raising this. I'll look into this

**Comment by markusz** [comment]
I was able to reproduce this and implemented a fix (see https://github.com/aws-samples/live-to-vod-workflow-using-aws-serverless-platform/pull/5) - @gmarchand Can you verify that this solves the problem for you

Thanks

**Comment by markusz** [comment]
Closing. Please reopen if necessary
